version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodeapp
hooks:
  BeforeInstall:
    - location: scripts/create_directory.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu

