version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/nodeapp

permissions:
  - object: /home/ubuntu/nodeapp
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/setup_environment.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root   # runs npm as root to avoid EACCES

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: ubuntu  # pm2 runs as ubuntu user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu

